---
- hosts: all
  vars_files: 
    - vars/default.yml
  
  roles:
    - role: nginx
    - role: geerlingguy.firewall
    - role: geerlingguy.security
    - role: nginx
    - role: geerlingguy.certbot
                                              


