---
- hosts: all
  become: true
  vars_files: 
    - vars/default.yml
  
  roles:
    - role: common
    - role: geerlingguy.security
    - role: nginx
    - role: geerlingguy.certbot
    - role: prosody
                                              


